In [2]:
# Data types

# Numeric
n2 <- 15 # Double precision by default
n2
typeof(n2)

[1] 15

[1] "double"

In [3]:
# Character

c1 <- "c"
c1
typeof(c1)

[1] "c"

[1] "character"

In [4]:
c2 <- "a string of text"
c2
typeof(c2)

[1] "a string of text"

[1] "character"

In [5]:
# Logical

l1 <- TRUE
l1
typeof(l1)

[1] TRUE

[1] "logical"

In [6]:
l2 <- F
l2
typeof(l2)

[1] FALSE

[1] "logical"

In [7]:
# Vector

v1 <- c(1,2,3,4,5)  # c stands for "combine"
v1
is.vector(v1)

[1] 1 2 3 4 5

[1] TRUE

In [8]:
v2 <- c("a","b","c")
v2
is.vector(v2)

[1] "a" "b" "c"

[1] TRUE

In [10]:
v3 <- c(TRUE, TRUE, FALSE, FALSE, TRUE)
v3
is.vector(v3)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] TRUE

In [12]:
# Matrix

m1 <- matrix(c(T,T,F,F,T,F), nrow=2)
m1

[,1] [,2]  [,3] 
[1,] TRUE FALSE  TRUE
[2,] TRUE FALSE FALSE

In [20]:
m2 <- matrix(c("a","b",
              "c","d"))
m2

[,1]
[1,] a   
[2,] b   
[3,] c   
[4,] d

In [18]:
m2 <- matrix(c("a","b",
              "c","d"),
             nrow=2)
m2

[,1] [,2]
[1,] a    c   
[2,] b    d

In [19]:
m2 <- matrix(c("a","b",
              "c","d"),
             nrow=2,
             byrow=T)
m2

[,1] [,2]
[1,] a    b   
[2,] c    d

In [32]:
# Data frame

# Can combine vectors of the same length

vNumeric   <- c(1,2,3)
vCharacter <- c("a","b","c")
vLogical   <- c(T,F,T)

dfa <- cbind(vNumeric,vCharacter,vLogical) # cbin refers to "column bind"
dfa # Matrix of one data type
typeof(dfa)

vNumeric vCharacter vLogical
[1,] 1        a          TRUE    
[2,] 2        b          FALSE   
[3,] 3        c          TRUE

[1] "character"

In [31]:
df <- as.data.frame(cbind(vNumeric,vCharacter,vLogical))  # data types of each of the variables
df


vNumeric vCharacter vLogical
1 1        a          TRUE    
2 2        b          FALSE   
3 3        c          TRUE

[1] "list"

In [37]:
typeof(df)
typeof(df$vNumeric)
typeof(df$vCharacter)
typeof(df$vLogical)

[1] "list"

[1] "character"

[1] "character"

[1] "character"

In [40]:
# List

o1 <- c(1,2,3)
o2 <- c("a","b","c","d")
o3 <- c(T,F,T,T,F)

list1 <- list(o1,o2,o3)
list1

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [41]:
list2 <- list(o1, o2, o3, list1)   # Lists within lists!
list2

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

[[4]]
[[4]][[1]]
[1] 1 2 3

[[4]][[2]]
[1] "a" "b" "c" "d"

[[4]][[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

In [42]:
# Coercing Types

## Automatic coercion

# Goes to "least restrictive" data type

(coerce1 <- c(1,"b", TRUE))
typeof(coerce1)

[1] "1"    "b"    "TRUE"

[1] "character"

In [43]:
# Coerce numeric to integer
(coerce2 <- 5)
typeof(coerce2)

[1] 5

[1] "double"

In [44]:
coerce3 <- as.integer(5)
typeof(coerce3)

[1] "integer"

In [45]:
## Coerce character to numeric

(coerce4 <- c("1","2","3"))
typeof(coerce4)

[1] "1" "2" "3"

[1] "character"

In [47]:
coerce5 <- as.numeric(c("1","2","3"))
typeof(coerce5)

[1] "double"

In [50]:
# Coerce matrix to data frame

coerce6 <- matrix(1:9, nrow=3)
coerce6
is.matrix(coerce6)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

In [53]:
coerce7 <- as.data.frame(matrix(1:9, nrow=3))
coerce7
is.data.frame(coerce7)

V1 V2 V3
1 1  4  7 
2 2  5  8 
3 3  6  9

[1] TRUE